# Generated by Django 4.1.3 on 2022-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_comments_options_remove_comments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_body',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
