# Generated by Django 4.1.3 on 2022-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, default='images/default no pic image.jpg', null=True, upload_to='images/'),
        ),
    ]
